_wandb:
    value:
        cli_version: 0.27.0
        e:
            0f6vmxr7de51snuo3a0cj6wlw2l6x80m:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_a6n6w5z8
                    - --params-file
                    - /tmp/launch_params_1ild6fs5
                    - --params-file
                    - /tmp/launch_params_djwz0z2q
                    - --params-file
                    - /tmp/launch_params_5qbbdka0
                    - --params-file
                    - /tmp/launch_params_jiu5vg9p
                    - --params-file
                    - /tmp/launch_params_g73aboqg
                    - --params-file
                    - /tmp/launch_params_owyl656i
                    - --params-file
                    - /tmp/launch_params_ijhk1awe
                    - --params-file
                    - /tmp/launch_params_lp04cwex
                    - --params-file
                    - /tmp/launch_params_22ztmso5
                    - --params-file
                    - /tmp/launch_params_7oudcdun
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "113121492992"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877015040"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-24T14:05:02.345908Z"
                writerId: 0f6vmxr7de51snuo3a0cj6wlw2l6x80m
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: ST_original
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: C5_g05_AB
ts:
    value: 0.2
