_wandb:
    value:
        cli_version: 0.27.0
        e:
            jro6fo87103e35ps3y4h4t8ywzip3bxn:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_cjq5etxm
                    - --params-file
                    - /tmp/launch_params_5_0gu0os
                    - --params-file
                    - /tmp/launch_params_e6t1mdi0
                    - --params-file
                    - /tmp/launch_params_jqb1s993
                    - --params-file
                    - /tmp/launch_params_nkj593o7
                    - --params-file
                    - /tmp/launch_params__ikuslxt
                    - --params-file
                    - /tmp/launch_params__m0u2qxm
                    - --params-file
                    - /tmp/launch_params_9t45m7s7
                    - --params-file
                    - /tmp/launch_params_8un15xyc
                    - --params-file
                    - /tmp/launch_params_abjcng3x
                    - --params-file
                    - /tmp/launch_params_ud6vrmqv
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "113881956352"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877002752"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-27T06:41:35.392357Z"
                writerId: jro6fo87103e35ps3y4h4t8ywzip3bxn
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: SingularTrajectory
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: C7_5j
ts:
    value: 0.2
