_wandb:
    value:
        cli_version: 0.27.0
        e:
            j4a5ujcqy48h60qjkq8wr6ka3rnff2kl:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_tjgyd5mf
                    - --params-file
                    - /tmp/launch_params_xck12sgc
                    - --params-file
                    - /tmp/launch_params_0xoioofx
                    - --params-file
                    - /tmp/launch_params_4ar3w0e8
                    - --params-file
                    - /tmp/launch_params_wmt9z7os
                    - --params-file
                    - /tmp/launch_params_feb1p9tg
                    - --params-file
                    - /tmp/launch_params_m6_5q3_4
                    - --params-file
                    - /tmp/launch_params_gogw9jp4
                    - --params-file
                    - /tmp/launch_params_y6l_jxpk
                    - --params-file
                    - /tmp/launch_params_sfbw8m91
                    - --params-file
                    - /tmp/launch_params_4__4njjf
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "112380764160"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877015040"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-20T14:53:05.952416Z"
                writerId: j4a5ujcqy48h60qjkq8wr6ka3rnff2kl
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: ST-warehouse-progress
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: ST_progress
ts:
    value: 0.2
