_wandb:
    value:
        cli_version: 0.27.0
        e:
            8109upmhaat4vh1nbmflkjmaxxuq8xu1:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_g68285ta
                    - --params-file
                    - /tmp/launch_params_v2q1v1cx
                    - --params-file
                    - /tmp/launch_params_xqt24_xc
                    - --params-file
                    - /tmp/launch_params_anw19j7r
                    - --params-file
                    - /tmp/launch_params_i38n6dg8
                    - --params-file
                    - /tmp/launch_params_myayjv46
                    - --params-file
                    - /tmp/launch_params_87clpz57
                    - --params-file
                    - /tmp/launch_params_0x_zwp22
                    - --params-file
                    - /tmp/launch_params_2sc9lrex
                    - --params-file
                    - /tmp/launch_params_fwja0yx9
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "103383064576"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877010944"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-19T11:11:38.132529Z"
                writerId: 8109upmhaat4vh1nbmflkjmaxxuq8xu1
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: ST_MPC_filter
ts:
    value: 0.2
