_wandb:
    value:
        cli_version: 0.27.0
        e:
            y55a7inlfkvq5zbwe64xnx6uqeczse0x:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_zmcte5m7
                    - --params-file
                    - /tmp/launch_params_919slh0u
                    - --params-file
                    - /tmp/launch_params_v779ka_a
                    - --params-file
                    - /tmp/launch_params_akw4iw4m
                    - --params-file
                    - /tmp/launch_params_919j83s1
                    - --params-file
                    - /tmp/launch_params_0klac0ml
                    - --params-file
                    - /tmp/launch_params__lx5p6_v
                    - --params-file
                    - /tmp/launch_params_3otde9uj
                    - --params-file
                    - /tmp/launch_params_evc73mw1
                    - --params-file
                    - /tmp/launch_params_lf8ssrs5
                    - --params-file
                    - /tmp/launch_params_vck0f62r
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "113017892864"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877015040"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-22T15:19:37.736667Z"
                writerId: y55a7inlfkvq5zbwe64xnx6uqeczse0x
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: zara2
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: C4lite_g05_ST_original
ts:
    value: 0.2
