_wandb:
    value:
        cli_version: 0.27.0
        e:
            upesmpby5sh2fqywyr5503jq7u4fjzi3:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_p4fgyh5o
                    - --params-file
                    - /tmp/launch_params_utj35xqs
                    - --params-file
                    - /tmp/launch_params_peh0ui_m
                    - --params-file
                    - /tmp/launch_params_fykh1ax4
                    - --params-file
                    - /tmp/launch_params_kolt3_ar
                    - --params-file
                    - /tmp/launch_params_chxme9lw
                    - --params-file
                    - /tmp/launch_params_r4tl73c9
                    - --params-file
                    - /tmp/launch_params_hrzzyrxi
                    - --params-file
                    - /tmp/launch_params_9x67i9ea
                    - --params-file
                    - /tmp/launch_params_qh9en8rs
                    - --params-file
                    - /tmp/launch_params_gzk0fh7m
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "113076621312"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877015040"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-23T08:13:35.894011Z"
                writerId: upesmpby5sh2fqywyr5503jq7u4fjzi3
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: zara2
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: C4lite_g05_ST_original
ts:
    value: 0.2
