_wandb:
    value:
        cli_version: 0.27.0
        e:
            y39jk2e1qqwaj0s9v04edru52szbpmgb:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_uemxmww2
                    - --params-file
                    - /tmp/launch_params_p9xtkdbp
                    - --params-file
                    - /tmp/launch_params_wf6id5gr
                    - --params-file
                    - /tmp/launch_params_43hgmtn3
                    - --params-file
                    - /tmp/launch_params_p4shmwr5
                    - --params-file
                    - /tmp/launch_params_xdlisgq6
                    - --params-file
                    - /tmp/launch_params_bq8urqly
                    - --params-file
                    - /tmp/launch_params_m8nqaytk
                    - --params-file
                    - /tmp/launch_params_3d51y_im
                    - --params-file
                    - /tmp/launch_params_an3d4ptc
                    - --params-file
                    - /tmp/launch_params_j56oy0pv
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "112608649216"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877015040"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-22T07:32:22.177023Z"
                writerId: y39jk2e1qqwaj0s9v04edru52szbpmgb
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: ST-warehouse-progress
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: C3_ST_progress
ts:
    value: 0.2
