_wandb:
    value:
        cli_version: 0.27.0
        e:
            b8adh8oqqgsot2mzhdi7b4u0cod160jp:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_mkunujgw
                    - --params-file
                    - /tmp/launch_params_kyzj0wfi
                    - --params-file
                    - /tmp/launch_params_j_1wxmr7
                    - --params-file
                    - /tmp/launch_params_twr2ewe4
                    - --params-file
                    - /tmp/launch_params_8u14krdb
                    - --params-file
                    - /tmp/launch_params_9mim4thg
                    - --params-file
                    - /tmp/launch_params_8feec9ud
                    - --params-file
                    - /tmp/launch_params_28bx14lb
                    - --params-file
                    - /tmp/launch_params_8h_kcy3c
                    - --params-file
                    - /tmp/launch_params_vvh0hv8o
                    - --params-file
                    - /tmp/launch_params_5k3go_w9
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "113139494912"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877015040"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-25T03:38:58.036379Z"
                writerId: b8adh8oqqgsot2mzhdi7b4u0cod160jp
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 13
                - 16
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: ST_original
qdynobs:
    value: 250
qrpd:
    value: 5
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: C5lite_g05
ts:
    value: 0.2
