_wandb:
    value:
        cli_version: 0.27.0
        e:
            x3888dumtqldh42zufg6p3e7z7ewviqj:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_e7ky2px7
                    - --params-file
                    - /tmp/launch_params_mpttw16i
                    - --params-file
                    - /tmp/launch_params_rmwozzls
                    - --params-file
                    - /tmp/launch_params_7asoh89l
                    - --params-file
                    - /tmp/launch_params_bph2_w3h
                    - --params-file
                    - /tmp/launch_params_pm7m3w7u
                    - --params-file
                    - /tmp/launch_params_wbab1tt8
                    - --params-file
                    - /tmp/launch_params_z8oxsseg
                    - --params-file
                    - /tmp/launch_params_1315mdoe
                    - --params-file
                    - /tmp/launch_params_txbl6phk
                    - --params-file
                    - /tmp/launch_params_pvxvtsfm
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "113038049280"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877002752"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-26T09:53:40.011430Z"
                writerId: x3888dumtqldh42zufg6p3e7z7ewviqj
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: SingularTrajectory
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: C7_5f
ts:
    value: 0.2
