_wandb:
    value:
        cli_version: 0.27.0
        e:
            yqzbcu6a5n9xiklxxwrtrfnmxnmsucpv:
                args:
                    - --ros-args
                    - -r
                    - __node:=mpc_trajectory_tracker_node
                    - -r
                    - __ns:=/zmr_X
                    - --params-file
                    - /tmp/launch_params_80z0q8nv
                    - --params-file
                    - /tmp/launch_params_tjv4b_on
                    - --params-file
                    - /tmp/launch_params_s88qfy10
                    - --params-file
                    - /tmp/launch_params_89u1w6cf
                    - --params-file
                    - /tmp/launch_params_jniejij8
                    - --params-file
                    - /tmp/launch_params_1nsa3cmh
                    - --params-file
                    - /tmp/launch_params_hoajl6vz
                    - --params-file
                    - /tmp/launch_params_7w8y7gms
                    - --params-file
                    - /tmp/launch_params_1egsrutv
                    - --params-file
                    - /tmp/launch_params_h3jde53k
                    - --params-file
                    - /tmp/launch_params_pxig9hcr
                codePath: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                codePathLocal: install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982795165696"
                        used: "112385990656"
                email: awdguyi0208@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-addf9c25-6a6b-322b-5099-6afc943dccb4
                host: michael-system-product-name-local
                memory:
                    total: "32877015040"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.35
                program: /home/michael/ros2_ws_test/install/zmr_mpc/lib/zmr_mpc/mpc_trajectory_tracker_node
                python: CPython 3.10.12
                root: /home/michael/ros2_ws_test
                startedAt: "2026-05-20T14:57:41.852875Z"
                writerId: yqzbcu6a5n9xiklxxwrtrfnmxnmsucpv
        m: []
        python_version: 3.10.12
        t:
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.10.12
            "5": 0.27.0
            "12": 0.27.0
            "13": linux-x86_64
N_hor:
    value: 20
ang_acc_penalty:
    value: 2
predictor_variant:
    value: ST-warehouse-progress
qdynobs:
    value: 250
qrpd:
    value: 30
qstcobs:
    value: 300
qvel:
    value: 10
scenario:
    value: ST_progress
ts:
    value: 0.2
